<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyName>DotNetCore.HayateOP.Extensions.Diagnostics</AssemblyName>
        <PackageId>DotNetCore.HayateOP.Extensions.Diagnostics</PackageId>
        <Description>DotNetCore Hayate Object Pool Diagnostics Extensions</Description>
    </PropertyGroup>

	<PropertyGroup>
		<RootNamespace />
	</PropertyGroup>

    <Import Project="..\..\common.props" />

    <Import Project="references.props" />

</Project>
