<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
        <LangVersion>default</LangVersion>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace/>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HayateOP.Extensions.DependencyInjection\HayateOP.Extensions.DependencyInjection.csproj" />
      <ProjectReference Include="..\HayateOP\HayateOP.csproj" />
    </ItemGroup>

</Project>
