<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>default</LangVersion>
        <RootNamespace />
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HayateOP.Extensions.DependencyInjection\HayateOP.Extensions.DependencyInjection.csproj" />
      <ProjectReference Include="..\HayateOP\HayateOP.csproj" />
    </ItemGroup>

    <!--<ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
      <PackageReference Include="Microsoft.OpenApi" Version="3.3.1" />
    </ItemGroup>-->

</Project>
